apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: audiohub-db
spec:
  instances: 2
  imageName: 'cerit.io/cloudnative-pg/postgresql:15.0'
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true

  bootstrap:
   initdb:
     database: audiohub
     owner: audiohub

  postgresql:
    enableAlterSystem: true
    parameters:
      wal_keep_size: 5GB
      ssl_min_protocol_version: TLSv1.2
      ssl_max_protocol_version: TLSv1.3

  replicationSlots:
    highAvailability:
      enabled: true

  resources:
    requests:
      memory: "1Gi"
      cpu: 1
    limits:
      memory: "2Gi"
      cpu: 1

  storage:
    size: 10Gi
    storageClass: nfs-csi